apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loadtest42-poi-map-app-dev
  annotations:
    argocd/app-name: loadtest42-poi-map-app-dev
    backstage.io/kubernetes-id: loadtest42-poi-map-app
    backstage.io/kubernetes-namespace: loadtest42
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/loadtest42-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/loadtest42/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/loadtest42/deployments/loadtest42-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/loadtest42-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://loadtest42-poi-map-app-loadtest42.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/loadtest42"
  system: workshop-system-loadtest42
  consumesApis:
    - gateway-api-loadtest42
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-loadtest42
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/loadtest42"
